name: Node.js

on:
  push:
  pull_request:
  schedule:
    # Check if it works with current dependencies (weekly on Wednesday 4:32 UTC)
    - cron: '32 4 * * 3'

jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16
          - 14
          - 12
        working-directory:
          - core
          - telegraf-inline-menu
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: ${{ matrix.working-directory }}
      - run: npm test
        working-directory: ${{ matrix.working-directory }}
